name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for Node.js backend
        run: npm install
        working-directory: ./nodejs-app

      - name: Run tests for Node.js backend
        run: npm test
        working-directory: ./nodejs-app

      - name: Install dependencies for React frontend
        run: npm install
        working-directory: ./react-app

      - name: Build React app
        run: npm run start
        working-directory: ./react-app/

      - name: SSH into EC2 and deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/mern-crud/mern-crud-app-master/nodejs-app
            git pull origin main
            npm install
            pm2 restart all

